### ISSUE TITLE
May be a bad idea to use client/server folder names inside imports

### ISSUE THREAD

**Issue by ffxsam** [meteor/todos#147] opened 2016-06-03 17:54 UTC
(Per https://github.com/meteor/meteor/issues/7153)

Apparently having folders called `client` and `server`, even within the `imports` folder, causes problem for the test runner.

**Comment by tmeasday** [comment] 2016-06-04 03:21
I think maybe the build tool shouldn't make the `client/server` distinction inside the `imports/` directory, but I think we what are doing in this app is OK..

**Comment by hwillson** [comment] 2016-10-04 19:30
As discussed in meteor/meteor#7153, the todos app is working as intended. Closing this off.

**Closed by hwillson** 2016-10-04 19:30 UTC
