### ISSUE TITLE
Any interest in a Vue port?

### ISSUE THREAD

**Issue by sethmurphy18** [meteor/todos#243] opened 2017-08-23 03:51 UTC
Since this is the quintessential app to show what Meteor is capable of, is there any interest in the Meteor community or development group to see a Vue port of this? I would be willing to take on the task if needed.

**Comment by hwillson** [comment] 2017-08-23 11:35
I think a Vue port would be great @sethmurphy18! If you're interested in working on one, that would be awesome!

**Comment by sethmurphy18** [comment] 2017-08-23 19:09
On it then

**Comment by sethmurphy18** [comment] 2017-08-23 22:11
Progress is being made. App component is 100% finished. Having a few issues due to translation issues between React and Vue, but it is definitely manageable.

```vue
<template>
  <div id="container" v-bind:class="menuOpen ? 'menu-open' : null">
    <section id="menu">
      <lanugage-toggle></lanugage-toggle>
      <user-menu v-bind:user="user" v-bind:logout="logout"></user-menu>
      <list-list v-bind:lists="lists"></list-list>
    </section>

    <connection-notification v-if="showConnectionIssue && !connected"></connection-notification>
    <div class="content-overlay" v-on:click="closeMenu()"></div>
    <div id="content-container">
      <loading v-if="loading"></loading>
      <router-view v-else></router-view>
    </div>
  </div>
</template>

<script>
// Meteor imports
import { Meteor } from 'meteor/meteor';

// API imports
import { Lists } from '../../api/lists/lists.js';

// Component imports
import UserMenu from '../components/UserMenu.vue';
import ListList from '../components/ListList.vue';
import LanguageToggle from '../components/LanguageToggle.vue';
import ConnectionNotification from '../components/ConnectionNotification.vue';
import Loading from '../components/Loading.jsx';

const CONNECTION_ISSUE_TIMEOUT = 5000;

export default {
  components: {
    'language-toggle': LanguageToggle,
    'user-menu': UserMenu,
    'list-list': ListList,
    'connectionNotification': ConnectionNotification,
    loading: Loading,
  },

  props: {
    user: Object,
    connected: Boolean,
    loading: Boolean,
    lists: Array,
    menuOpen: Boolean,
  },

  data() {
    return {
      menuOpen: false,
      showConnectionIssue: false,
      connected: Meteor.status().connected,
    };
  },

  methods: {
    logout() {
      Meteor.logout();

      if (this.$router.params.id) {
        const list = Lists.findOne(this.$router.params.id);

        if (list.userId) {
          const publicList = Lists.findOne({ userID: { $exists: false } });
          this.$router.push(`/lists/${publicList._id}`);
        }
      }
    },

    toggleMenu(menuOpen = !this.menuOpen) {
      this.menuOpen = menuOpen;
    },

    closeMenu() {
      this.toggleMenu(false);
    }
  },

  created() {
    setTimeout(() => {
      this.showConnectionIssue = true;
    }, CONNECTION_ISSUE_TIMEOUT);
  }
}
</script>

<style lang="less">
@import '../stylesheets/utils.less';

@menu-width: 270px;
@column: 5.55555%;

body {
  .position(absolute, 0, 0, 0, 0);
  background-color: #315481;
  background-image: linear-gradient(to bottom, #315481, #918e82 100%);
  background-repeat: no-repeat;
  background-attachment: fixed;
}

#container {
  .position(absolute, 0, 0, 0, 0);

  @media screen and (min-width: 60em) {
    left: @column;
    right: @column;
  }

  @media screen and (min-width: 80em) {
    left: 2*@column;
    right: 2*@column;
  } // Hide anything offscreen
  overflow: hidden;
}

#menu {
  .position(absolute, 0, 0, 0, 0, @menu-width);
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

#content-container {
  .position(absolute, 0, 0, 0, 0);
  transition: all 200ms ease-out;
  transform: translate3d(0, 0, 0);
  background: @color-tertiary;
  opacity: 1;

  @media screen and (min-width: 40em) {
    left: @menu-width;
  }

  .content-scrollable {
    .position(absolute, 0, 0, 0, 0);
    transform: translate3d(0, 0, 0);
    overflow-y: auto;
    -webkit-overflow-scrolling: touch;
  } // Toggle menu on mobile
  .menu-open & {
    transform: translate3d(@menu-width, 0, 0);
    opacity: .85;
    left: 0;

    @media screen and (min-width: 40em) {
      // Show menu on desktop, negate .menu-open
      transform: translate3d(0, 0, 0); //reset transform and use position properties instead
      opacity: 1;
      left: @menu-width;
    }
  }
}

// Transparent screen to prevent interactions on content when menu is open
.content-overlay {
  .position(absolute, 0, 0, 0, 0);
  cursor: pointer;

  .menu-open & {
    transform: translate3d(@menu-width, 0, 0);
    z-index: 1;
  } // Hide overlay on desktop
  @media screen and (min-width: 40em) {
    display: none;
  }
}
</style>
```

**Comment by sethmurphy18** [comment] 2017-08-27 09:58
Ok, I am having some issues, so I am going to open an RFC from the Meteor team. Vue and Meteor do get along, barely, except in one regard: reactivity. Tracker and Vue simply do **not** work together. I have found a package that allows me to use subscriptions: [vue-meteor-tracker](https://github.com/meteor-vue/vue-meteor-tracker), however it has 1 huge issue, I can only use 1 subscription per component. That's it. I can use more, but that would require using a modified version of [vue](https://github.com/mitar/vue.git#meteor) and a modified version of [tracker](https://github.com/meteor-vue/tracker/tree/2348458cd46e60adce821139efad7ae634336d00). While I could very easily do this, I think it kind of defeats the purpose of the todos app, which is to highlight how easy and flexible Meteor is. Also, it would appear @mitar has been working on a port of the [todos app](https://github.com/meteor-vue/todomvc) already. That said, I have 3 options for this app:

1. I can try to rewrite the plugin I am using to see if I can make it work
2. I can use [vuex](https://github.com/vuejs/vuex) and track everything using states and create a literal single page app (single route too)
3. I can use apollo, and go the graphql route, since apollo and vue are fine together...I think.

In terms of difficulty, I would say these are all fairly close. Apollo is only difficult because of having to redo the entire API part of the app.

**Comment by mitar** [comment] 2017-08-27 10:05
Why not use fork of vue and modified version of tracker? They are drop-in replacements and then you can just use multiple subscriptions per component and full reactivity and everything you are used to. Just try out [vue todo app](https://github.com/meteor-vue/todomvc). Works like a charm. :-)

**Comment by sethmurphy18** [comment] 2017-08-27 10:15
I am getting about to that point. This is very annoying. I am not knocking the vue-meteor-tracker package, but it's limitations are kinda infuriating.

**Comment by sethmurphy18** [comment] 2017-08-27 10:18
I'll let you look over what I have @mitar and see what you think. I hate showing my code in progress, since it is definitely not my best, but maybe you can see something I am missing.

https://github.com/eagerestwolf/todos-vue-meteor

**Comment by sethmurphy18** [comment] 2017-08-27 10:20
Oh btw, ignore all the test data. I literally ripped those straight from the react branch so I would remember to make Vue versions later.

**Comment by sethmurphy18** [comment] 2017-08-28 07:14
Ok @mitar I hate to bother you...again...but I have hit a stumbling block. I cannot get the subs to run at all now, and I am not sure what I am doing wrong. I switched to your version of Vue and your version of Tracker, but they just won't run. Any suggestions? I updated the code in the repo.

**Comment by mwarren2** [comment] 2017-09-02 12:20
@sethmurphy18 Glad to see that you are on to this. You seem to have set something rolling, and noone need doubt your competence to deal with this.

But - correct me if I'm wrong - this isn't just about the todos-app, it's about Meteor/Vuejs as a whole.

So I just wanted to register a plea to MDG to put a bit of weight behind Meteor/Vuejs - even if it's just opening a few doors, talking about it, organizing stuff, and generally helping you with this.
We've had people giving up a load of spare time and everlasting thanks to them, however Meteor/Vuejs stuff is still in beta after a couple of years (I think), so let's be realistic.

And that's nobody's fault. I'm certainly not complaining. I'm grateful for the work that has been done (Akryum), which has enabled me to get [quasar-framework](http://quasar-framework.org) working with Meteor, which is what I personally am interested in.

@mitar has done some great work with Vuejs, but it looks like it has to stay as a fork, for the moment.

@hwillson  Any possibility of MDG getting involved? I can't see how this is going to be solved without MDG giving some input, and encouraging an official line.

I've been messing with Vuejs for over a year now, and I wish I could use it in anger. 
Noone has the slightest doubt that Vuejs would be good for Meteor.
But obviously it's difficult to feel confident putting it into a Meteor project while things are in a state of flux with the main projects still in beta.

**Comment by sethmurphy18** [comment] 2017-09-02 18:27
@mwarren2 I kinda disagree. Meteor/VueJS is far from even Beta. We still are at the point that using Vue with Meteor requires not only a patched version of a Meteor core package, `tracker`, but also a patched version of Vue itself. 

That said, I believe the Blaze team, of which I believe @mitar is a part of, has stated that they want to use Vue as Blaze 2.0. I have looked into writing a plugin to bridge the gaps between Meteor and Vue, but sadly I do not have enough knowledge about the inner workings of the Meteor Reactivity System to make it work correctly.

And, yes, you are correct, part of my intention with this was to demonstrate to MDG that Vue and Meteor would be an excellent pairing, however, it is not a very good pairing at this time due to the amount of problems I have encountered. I simply cannot get Meteor's Reactivity System to work with Vue's Reactivity System, even using a pactched `tracker` and `vue`, so I have put this project on the back burner for the time being. As it simply will not subscribe to anything on the Meteor side of things. I am still working on trying to make the 2 work, just working from a different approach like we had to do in the early days of React.

**Comment by mitar** [comment] 2017-09-02 19:21
> Meteor/VueJS is far from even Beta. 

I mean, it is stable. And working. And feature complete.

> We still are at the point that using Vue with Meteor requires not only a patched version of a Meteor core package, tracker, but also a patched version of Vue itself.

So? This is just a way to distribute a code. Once you do that, it works like you expect.

**Comment by mitar** [comment] 2017-09-02 19:23
>  simply cannot get Meteor's Reactivity System to work with Vue's Reactivity System, even using a pactched tracker and vue, so I have put this project on the back burner for the time being. As it simply will not subscribe to anything on the Meteor side of things. I am still working on trying to make the 2 work, just working from a different approach like we had to do in the early days of React.

You would have to create a smaller reproduction for me to be able to help you here. A ported TODO app here works great with Vue and Meteor:

https://github.com/meteor-vue/todomvc

See [example component here](https://github.com/meteor-vue/todomvc/blob/master/client/todos-display.vue): it is a great mix of Blaze and Blaze Components. Everything you expected, just that naming is slightly different. And of course, Vue template itself. (For the latter, Vue supports preprocessors so we could probably create blaze template -> vue template preprocessor.)

**Comment by pentatronix** [comment] 2017-12-04 18:53
What is the state of this?

**Comment by mitar** [comment] 2017-12-04 19:54
It is implemented, see the link: https://github.com/meteor-vue/todomvc

**Comment by hwillson** [comment] 2018-04-26 11:37
Hi all - there hasn't been any activity here in a bit, so I'm going to close this off for now. If anyone is interested in working on a Vue port, definitely let us know. Thanks!

**Closed by hwillson** 2018-04-26 11:37 UTC

**Comment by mitar** [comment] 2018-04-26 13:05
I mean, Vue port already exists. So I am not sure what would have to be done more?

**Comment by hwillson** [comment] 2018-04-26 13:13
Great - I think the OP was referring to a Vue port of this `todos` app, but either way https://github.com/meteor-vue/todomvc is awesome. Thanks!
