### ISSUE TITLE
When I am trying to run this app through command 'meteor' it is throwing a error.

### ISSUE THREAD

**Issue by suhaibaffan** [meteor/todos#185] opened 2016-09-23 02:49 UTC
Started proxy.                             
/Users//.meteor/packages/meteor-tool/.1.4.1_1.1h0re2h++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: EACCES: permission denied, open '/Users/projects/todos/.meteor/local/.resolver-result-cache.json.ika90h'
    at Error (native)

**Comment by hwillson** [comment] 2016-10-04 20:02
Within your `todos` directory, run a `meteor reset` and try starting the app again. Make sure you're running meteor using a non-privileged user account (so no `root` or `sudo`).

**Comment by 123batman** [comment] 2016-10-22 14:12
Hello,
I have a similar problem. `meteor reset` didn't help (same error). I am also not logged in as root. meteor works fine in a folder created by `meteor create <projectname>`
I am interested in the react branch. So I tried the react branch first but it didn't work either.

```
user@linux ~/sync/code$ git clone https://github.com/meteor/todos.git
<git output omitted>
user@linux ~/code/todos$ meteor npm install
<npm output omitted>
user@linux ~/code/todos$ meteor
~/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-104sw15/os.json'
    at Error (native)
user@linux ~/sync/code/todos$ meteor reset
~/.meteor/packages/meteor-tool/.1.4.1_2.354htk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-17a2929/os.json'
    at Error (native)
```

**Comment by musclor** [comment] 2016-10-22 16:58
Hi,

I have the same issue on Windows 10 when I try 

> meteor reset

```
C:\Users\Musclor\Documents\Meteor\todos\todos>meteor reset
C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\Musclor\AppData\Local\Temp\mt-p55ydt\os.json'
    at Error (native)
```

And that is what I got when I tried to run the app with 

> meteor

```
C:\Users\Musclor\Documents\Meteor\todos\todos>meteor
C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at DirWriter.ondrain (stream.js:41:14)
    at emitNone (events.js:67:13)
    at DirWriter.emit (events.js:166:7)
    at DirWriter._process (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:87:10)
    at DirWriter.end (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:53:8)
    at Entry.onend (stream.js:59:10)
    at emitNone (events.js:72:20)
    at Entry.emit (events.js:166:7)
    at Entry._read (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:124:12)
    at Entry.resume (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:95:8)
    at resume (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at DirWriter.<anonymous> (C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at DirWriter.emit (events.js:166:7)
    at C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:38:10
    at C:\Users\Musclor\AppData\Local\.meteor\packages\meteor-tool\1.4.1_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\mkdirp\index.js:30:20
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Reproduction path : 
1/ git clone https://github.com/meteor/todos -> ok
2/ meteor -> nok
3/ meteor reset -> nok

Hope it will help find the issue.

**Comment by hwillson** [comment] 2016-10-24 10:47
This issue isn't `todos` app specific. It's being tracked via the main meteor repo. Take a look at the discussions happening in one of the following (which propose a few workarounds).

meteor/meteor#7766
meteor/meteor#7806

Closing this since it's being tracked above.

**Closed by hwillson** 2016-10-24 10:47 UTC
Labels: question
